// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqtwvlnbpjuvxxmdttsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxdHd2bG5icGp1dnh4bWR0dHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDAzOTgsImV4cCI6MjA2ODY3NjM5OH0.21IsmfnfjOcAUfCdoXZlk28uYQvUnHHc2mWSmZ5ljWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});